all:
  children:
    local:
      children:
        desktops:
          hosts:
        devops:
          hosts:
            wsl:
            devbox:
    remote:
      children:
        azure:
          hosts:
            devbox:
        aws:
          hosts: